:: Create Configuration2024.xml file
echo ^<Configuration ID="ccad5fff-31a5-46e3-981c-b8070ebbf76d"^> > "C:\Office\Configuration2024.xml"
echo   ^<Add OfficeClientEdition="64" Channel="PerpetualVL2024"^> >> "C:\Office\Configuration2024.xml"
echo     ^<Product ID="ProPlus2024Volume" PIDKEY="XJ2XN-FW8RK-P4HMP-DKDBV-GCVGB"^> >> "C:\Office\Configuration2024.xml"
echo       ^<Language ID="en-us" /^> >> "C:\Office\Configuration2024.xml"
echo       ^<ExcludeApp ID="Lync" /^> >> "C:\Office\Configuration2024.xml"
echo       ^<ExcludeApp ID="OneDrive" /^> >> "C:\Office\Configuration2024.xml"
echo     ^</Product^> >> "C:\Office\Configuration2024.xml"
echo     ^<Product ID="VisioPro2024Volume" PIDKEY="B7TN8-FJ8V3-7QYCP-HQPMV-YY89G"^> >> "C:\Office\Configuration2024.xml"
echo       ^<Language ID="en-us" /^> >> "C:\Office\Configuration2024.xml"
echo       ^<ExcludeApp ID="Lync" /^> >> "C:\Office\Configuration2024.xml"
echo       ^<ExcludeApp ID="OneDrive" /^> >> "C:\Office\Configuration2024.xml"
echo     ^</Product^> >> "C:\Office\Configuration2024.xml"
echo     ^<Product ID="ProjectPro2024Volume" PIDKEY="FQQ23-N4YCY-73HQ3-FM9WC-76HF4"^> >> "C:\Office\Configuration2024.xml"
echo       ^<Language ID="en-us" /^> >> "C:\Office\Configuration2024.xml"
echo       ^<ExcludeApp ID="Lync" /^> >> "C:\Office\Configuration2024.xml"
echo       ^<ExcludeApp ID="OneDrive" /^> >> "C:\Office\Configuration2024.xml"
echo     ^</Product^> >> "C:\Office\Configuration2024.xml"
echo   ^</Add^> >> "C:\Office\Configuration2024.xml"
echo   ^<Property Name="SharedComputerLicensing" Value="0" /^> >> "C:\Office\Configuration2024.xml"
echo   ^<Property Name="FORCEAPPSHUTDOWN" Value="FALSE" /^> >> "C:\Office\Configuration2024.xml"
echo   ^<Property Name="DeviceBasedLicensing" Value="0" /^> >> "C:\Office\Configuration2024.xml"
echo   ^<Property Name="SCLCacheOverride" Value="0" /^> >> "C:\Office\Configuration2024.xml"
echo   ^<Property Name="AUTOACTIVATE" Value="1" /^> >> "C:\Office\Configuration2024.xml"
echo   ^<Updates Enabled="TRUE" /^> >> "C:\Office\Configuration2024.xml"
echo   ^<AppSettings^> >> "C:\Office\Configuration2024.xml"
echo     ^<User Key="software\microsoft\office\16.0\excel\options" Name="defaultformat" Value="51" Type="REG_DWORD" App="excel16" Id="L_SaveExcelfilesas" /^> >> "C:\Office\Configuration2024.xml"
echo     ^<User Key="software\microsoft\office\16.0\powerpoint\options" Name="defaultformat" Value="27" Type="REG_DWORD" App="ppt16" Id="L_SavePowerPointfilesas" /^> >> "C:\Office\Configuration2024.xml"
echo     ^<User Key="software\microsoft\office\16.0\word\options" Name="defaultformat" Value="" Type="REG_SZ" App="word16" Id="L_SaveWordfilesas" /^> >> "C:\Office\Configuration2024.xml"
echo   ^</AppSettings^> >> "C:\Office\Configuration2024.xml"
echo ^</Configuration^> >> "C:\Office\Configuration2024.xml"
pause